######################################################################
# Automatically generated by qmake (3.0) ??? ??? 17 12:01:35 2019
######################################################################

QT+=widgets
TEMPLATE = app
TARGET = test4
INCLUDEPATH += .

# Input
HEADERS += mywindow.hpp
SOURCES += main.cpp mywindow.cpp
