######################################################################
# Automatically generated by qmake (3.0) ??? ??? 17 09:49:22 2019
######################################################################

QT+=widgets
TEMPLATE = app
TARGET = test2
INCLUDEPATH += .

# Input
SOURCES += test2.cpp
